### ISSUE TITLE
Bus signals go out of bounds

### ISSUE THREAD

**Issue by pedrompt97** [Toroid-io/vcd2wavedrom#3] opened 2020-09-19 17:36 UTC
This issue is related to issues #1  and #2. Although a collapsed bus is recognized, when converted from .drom to an image, it goes out of bounds:

![Out_of_bounds](https://user-images.githubusercontent.com/43758431/93679745-66d4ee80-faa5-11ea-83a4-a0c8f0dac198.PNG)

I also notice that when a signal has more bits, it goes further out of bounds.
My testbench uses a clock with a period of 10 ns.

My VCD file (converted to .txt) is:
[ram_vcd.txt](https://github.com/Toroid-io/vcd2wavedrom/files/5250273/ram_vcd.txt)

The config file I used is:
```json
{
    "signal": {},
    "replace": {},
    "filter": [
        "tdp_ram_tb.clk",
        "tdp_ram_tb.data_a[7:0]]",
        "tdp_ram_tb.addr_a[3:0]",
        "tdp_ram_tb.en_a",
        "tdp_ram_tb.we_a",
        "tdp_ram_tb.q_a[7:0]",
        "tdp_ram_tb.data_b[7:0]",
        "tdp_ram_tb.addr_b[3:0]",
        "tdp_ram_tb.en_b",
        "tdp_ram_tb.we_b",
        "tdp_ram_tb.q_b[7:0]"
    ],
    "offset": 0,
    "samplerate": 10000,
    "clocks": ["clk"],
    "maxtime": 200000
}
```

**Comment by andresmanelli** [comment] 2020-09-20 10:09
Hello, could you test the branch `3_busdetection` ? I will merge the PR #4 if it works for you.

It would be nice if you test it with another dataset :)

I modified your config to match the new code (just the clock name):

```json
{
    "signal": {},
    "replace": {},
    "filter": [
        "tdp_ram_tb.clk",
        "tdp_ram_tb.data_a[7:0]]",
        "tdp_ram_tb.addr_a[3:0]",
        "tdp_ram_tb.en_a",
        "tdp_ram_tb.we_a",
        "tdp_ram_tb.q_a[7:0]",
        "tdp_ram_tb.data_b[7:0]",
        "tdp_ram_tb.addr_b[3:0]",
        "tdp_ram_tb.en_b",
        "tdp_ram_tb.we_b",
        "tdp_ram_tb.q_b[7:0]"
    ],
    "offset": 0,
    "samplerate": 10000,
    "clocks": ["tdp_ram_tb.clk"],
    "maxtime": 100000
}
```

**Comment by pedrompt97** [comment] 2020-09-21 12:49
Hello. I've tested the new branch, and the bus signals now seem to fit in bounds. However, there is an inconsistency regarding those signals when converting to drom vs when using gtkwave.

Drom:
![drom](https://user-images.githubusercontent.com/43758431/93768064-c4397e80-fc10-11ea-96af-0f500e3fb55d.PNG)

Gtkwave:
![gtkwave](https://user-images.githubusercontent.com/43758431/93767571-1f1ea600-fc10-11ea-9dc1-c782d2a39357.PNG)

For some reason, q_a seems to be 1 clock cycle early in comparinson with addr_a. I also expected 1 clock cycle of undefined q_a, since this signal is the output of a memory.

I'll also prepare some testbenches for other modules, and report the results using different datasets soon.

**Comment by andresmanelli** [comment] 2020-09-21 13:01
It'd be interesting to see if the same inconsistency is present for individual signals besides buses

**Comment by pedrompt97** [comment] 2020-09-21 13:46
It seems like it is.

Gtkwave:
![gtkwave](https://user-images.githubusercontent.com/43758431/93774422-28f8d700-fc19-11ea-9d5f-965ae766ff06.PNG)

Drom:
![drom](https://user-images.githubusercontent.com/43758431/93774424-2a2a0400-fc19-11ea-87d8-c255f4a03308.PNG)

**Comment by andresmanelli** [comment] 2020-09-21 15:27
I think I know what the problem is. Try changing the samplerate to 1000, you get a "proper" render (clock will be wrong) and scale will be very bad. But signal phase will be correct.

![image](https://user-images.githubusercontent.com/7302217/93785691-abd85c80-fc2e-11ea-8e27-3a6f043b94ea.png)

This is due to the sampling point: For example, `sp_rom_tb.r_en` changes just after the 3rd rising edge. This high state will be sampled on the 4th rising edge, not before.

Now, `hscale` on wavedrom is integer only (>= 1) (c.f. https://github.com/wavedrom/wavedrom/issues/50). So providing a smaller scale is not a solution.

If you apply a (hacky) 0.9 phase offset to the signal, it will render correctly:

![image](https://user-images.githubusercontent.com/7302217/93786114-34ef9380-fc2f-11ea-86ae-49cd87b421b6.png)

I'm thinking a proper way to deal with this is to provide the clockrate and samplerate separately, and compute the phase attribute for each signal.

Any thoughts ?

**Comment by pedrompt97** [comment] 2020-09-21 16:11
For the sp_rom, changing the samplerate does fix the signal phase, but when I do the same for the tdp_ram (the one that uses bus signals, the result seems to be far from expected.

![drom](https://user-images.githubusercontent.com/43758431/93790529-0f608b00-fc2b-11ea-9ad4-f199c4665721.PNG)

As for the clockrate and samplerate, my verilog has a 1ns/1ps timescale and a 10 timescales (10ns) period clk, so it would make sense to separate samplerate from clockrate. The most logical solution would be having a samplerate of 1ns (in this case), and using the WaveDrom attribute "period" to propely render the clock:

![drom](https://user-images.githubusercontent.com/43758431/93792285-3cae3880-fc2d-11ea-91ec-ff65b42ba2bc.PNG)

This, however, does not seem to fix the scaling problem, nor the error when using a bus signal.

**Comment by andresmanelli** [comment] 2021-04-16 07:50
Hey @pedrompt97 , it's been a while, sorry about that.

WIth the merge of #4 and #6 , the behavior from your last comment (`tdp_ram`) seems to be fixed (at least from a values point of view).

I looked into the scaling issue, but it's not trivial to compute the phases:

 - Some signals may be asynchronous (like `r_en`), so the phase is not valid for all the time range
 - Some signals may be synchronous to the falling edge, so this would need to be considered
 - Different signals may be synchronous with different clocks

The real fix whould be to have a floating point `hscale`..

I thing I will open a new issue, and close this one after I merge #6.

**Closed** 2021-04-16 11:37 UTC
